### PR TITLE
Add note about SDK version in readme

### PR DESCRIPTION
**Pull request by bdemers**
Added quick note per: https://devforum.okta.com/t/compatibility-issues-not-noted-between-okta-java-sdk-and-okta-spring-sdk/12159

### CODE REVIEW

**Comment by arvindkrishnakumar-okta** [comment]
@bdemers Can we close this considering we've added https://github.com/okta/okta-spring-boot#spring-boot-version-compatibility?

**Review by arvindkrishnakumar-okta — APPROVED** [review]

**Comment by mraible** [comment]
@arvindkrishnakumar-okta Can this be merged?

**Comment by arvindkrishnakumar-okta** [comment]
> @arvindkrishnakumar-okta Can this be merged?

@mraible I don't think this change is still relevant. We've already at `2.1.0`.

**Comment by mraible** [comment]
You are correct. We should figure out a way to automatically add it for releases.

**Comment by mraible** [comment]
I deleted my last comment because I thought this was a different PR. @bdemers initially created this PR. I think it can be closed.

**Pull request closed without merging**
